# Generated by Django 4.2 on 2024-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Локация')),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
